version: "3"

services:
  postgresql:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_USER: 123
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sclass2
    ports:
      - "6543:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
    driver: local
