version: "3"

services:
  postgresql:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_USER: 123
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sclass2
      ports:
        - "5432:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgresql:
    driver: local
